### ISSUE TITLE
Plugin complains about update 2014-02-05 after installing

### ISSUE THREAD

**Issue by poulpoulsen** [lisps/ajaxedit#2]
hello,
i use dokuwiki hrun and want to use tags.
after installing your ajax-helper plugin dokuwiki complains about updating on new version 2014-02-05, but i did install directly within dokuwiki.
therefore i think that the installed version should be the newest?
any clues?

Regards
Poul

**Comment by peterfromearth** [comment]
I suppose I used to wrong download url link on dokuwiki.org
